// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASOczOrNYLvDQBZoqM7q5ulcNVQznnKMw',
    appId: '1:234627670256:web:58f6108578e1a21a256235',
    messagingSenderId: '234627670256',
    projectId: 'sheraa-95d17',
    authDomain: 'sheraa-95d17.firebaseapp.com',
    storageBucket: 'sheraa-95d17.appspot.com',
    measurementId: 'G-VW5729SFJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOkJjJBiUGWqx_xNOeD_lHhWNr7APyhgY',
    appId: '1:234627670256:android:fa6df54f086cbf23256235',
    messagingSenderId: '234627670256',
    projectId: 'sheraa-95d17',
    storageBucket: 'sheraa-95d17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7S-JuoY5BmpQ3gkCkW-Dge1S7Mdcehz4',
    appId: '1:234627670256:ios:44341e683995b17c256235',
    messagingSenderId: '234627670256',
    projectId: 'sheraa-95d17',
    storageBucket: 'sheraa-95d17.appspot.com',
    iosClientId: '234627670256-dknlp0ti17fgqqpacudv9s5kdk6t1fm2.apps.googleusercontent.com',
    iosBundleId: 'com.shyam.sheraa.sheraa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7S-JuoY5BmpQ3gkCkW-Dge1S7Mdcehz4',
    appId: '1:234627670256:ios:e6a4e9b825bfb66c256235',
    messagingSenderId: '234627670256',
    projectId: 'sheraa-95d17',
    storageBucket: 'sheraa-95d17.appspot.com',
    iosClientId: '234627670256-0mi0c0of00qupvaho8vrc3981k3ndh6q.apps.googleusercontent.com',
    iosBundleId: 'com.shyam.sheraa.sheraa.RunnerTests',
  );
}